#!/bin/bash

WIDTH=`xdpyinfo | grep 'dimensions:' | cut -f 2 -d : | cut -f 1 -d x`
HALF=`expr $WIDTH / 2`

if [[ $1 == 'left' ]];
then
  wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz && wmctrl -r :ACTIVE: -b add,maximized_vert && wmctrl -r :ACTIVE: -e 0,0,0,$HALF,-1

elif [[ $1 == 'right' ]]
then
  wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz && wmctrl -r :ACTIVE: -b add,maximized_vert && wmctrl -r :ACTIVE: -e 0,$HALF,0,$HALF,-1

else
  wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
fi

